### ISSUE TITLE
uploadRobotFile returns Action Error : java.lang.NullPointerException

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-robot-extension#26]
Hello, while trying to use the uploadRobotFile action a java.lang.NullPointerException occurs.
![image](https://github.com/cerberustesting/cerberus-robot-extension/assets/16339891/942930f8-1123-4492-a828-681f23cbdb14)

the action is configured like this:
![image](https://github.com/cerberustesting/cerberus-robot-extension/assets/16339891/46b87eac-9a9a-49ef-aae4-75289af76135)

Can you please advise?

**Comment by vertigo17** [comment]
Can you confirm that the robot extention runs on a windows system ?
You configured a Windows path and logs  looks like docker based so I guess running under Linux.
If using a standard docker image path should be more like /home/seluser/Downloads/test.json
That way the file will be created on the robot side directly inside Download folder. Ready to be uploaded from the browser to your application.

**Comment by j0hnsa** [comment]
It does run on windows system, is this action limited to linux hosts?

**Comment by vertigo17** [comment]
There are no reason that this shouls not work on windows.
I will have a look why npe was raized

**Comment by j0hnsa** [comment]
I've tested with linux and the error seems to be present too, maybe I'm missing something
![VirtualBox_centos9_15_07_2024_22_50_32](https://github.com/user-attachments/assets/c13d5aea-440d-4a67-8cf4-ce07297a5daf)
![VirtualBox_centos9_15_07_2024_22_51_03](https://github.com/user-attachments/assets/5c41ed78-2186-447a-a216-ebb3d30a2b0b)

**Comment by vertigo17** [comment]
Thanks for the log. I will try to reproduce that.

**Comment by vertigo17** [comment]
A couple of question that may help to identify the issue:
Did you secure that folder C:\CerberusData\ or whatever folder you specified on your test under a linux docker image existed ? 
Can you test putting /home/seluser./downloads/test.json after making sure that folder /home/seluser/Downloads/ exist ?
Also secure that parameter -a (--authorisedFolderScope) has been feed with /home/seluser/Downloads/ or docker compose include it this way:

```
  selenium-node-chrome:
    image: cerberus-node-chrome
    environment:
      HUB_HOST: selenium-hub
      SE_OPTS: -servlets org.cerberus.robot.extension.sikuli.ExecuteSikuliAction -servlets org.cerberus.robot.extension.filemanagement.ExecuteFilemanagementAction -servlets org.cerberus.robot.extension.management.ExecuteManagementAction
      JAVA_OPTS: -DauthorisedFolderScope=/home/seluser/Downloads
    depends_on:
      - selenium-hub
    expose:
      - "5900"
    ports:
      - "XXXXXX:5900"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    shm_size: 512mb
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1548M

```
